name: hello world deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
	uses: actions/checkout@v2
	
      - name: Execute Remote SSH & Clone
        uses: garygrossgarten/github-action-ssh@release
        with: 
          host: ${{ secrets.HOST_STAGING }}
          username: ${{ secrets.USERNAME_STAGING }}
          privatekey: ${{ secrets.SSH_SECRET_STAGING }}
	  command: |
